/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionRouteImport } from './routes/solution'
import { Route as RoiCalculatorRouteImport } from './routes/roi-calculator'
import { Route as ProblemRouteImport } from './routes/problem'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin_.forgot-password'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminNavigationRouteImport } from './routes/admin.navigation'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLocationsRouteImport } from './routes/admin.locations'
import { Route as AdminLiveVisitorsRouteImport } from './routes/admin.live-visitors'
import { Route as AdminLanguagesRouteImport } from './routes/admin.languages'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminInquiriesRouteImport } from './routes/admin.inquiries'
import { Route as AdminHeroRouteImport } from './routes/admin.hero'
import { Route as AdminFaqRouteImport } from './routes/admin.faq'
import { Route as AdminEconomicFeasibilityRouteImport } from './routes/admin.economic-feasibility'
import { Route as AdminDesignRouteImport } from './routes/admin.design'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminContactInfoRouteImport } from './routes/admin.contact-info'
import { Route as AdminBackupRouteImport } from './routes/admin.backup'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as ApiPublicVisitorContextRouteImport } from './routes/api/public/visitor-context'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as ApiPublicContactNotifyRouteImport } from './routes/api/public/contact-notify'
import { Route as ApiMediaDriveUploadRouteImport } from './routes/api/media.drive-upload'

const SolutionRoute = SolutionRouteImport.update({
  id: '/solution',
  path: '/solution',
  getParentRoute: () => rootRouteImport,
} as any)
const RoiCalculatorRoute = RoiCalculatorRouteImport.update({
  id: '/roi-calculator',
  path: '/roi-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemRoute = ProblemRouteImport.update({
  id: '/problem',
  path: '/problem',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/admin_/forgot-password',
  path: '/admin/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNavigationRoute = AdminNavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocationsRoute = AdminLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveVisitorsRoute = AdminLiveVisitorsRouteImport.update({
  id: '/live-visitors',
  path: '/live-visitors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLanguagesRoute = AdminLanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqRoute = AdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEconomicFeasibilityRoute =
  AdminEconomicFeasibilityRouteImport.update({
    id: '/economic-feasibility',
    path: '/economic-feasibility',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDesignRoute = AdminDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactInfoRoute = AdminContactInfoRouteImport.update({
  id: '/contact-info',
  path: '/contact-info',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupRoute = AdminBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicVisitorContextRoute = ApiPublicVisitorContextRouteImport.update({
  id: '/api/public/visitor-context',
  path: '/api/public/visitor-context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactNotifyRoute = ApiPublicContactNotifyRouteImport.update({
  id: '/api/public/contact-notify',
  path: '/api/public/contact-notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaDriveUploadRoute = ApiMediaDriveUploadRouteImport.update({
  id: '/api/media/drive-upload',
  path: '/api/media/drive-upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/problem': typeof ProblemRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/solution': typeof SolutionRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/contact-info': typeof AdminContactInfoRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/design': typeof AdminDesignRoute
  '/admin/economic-feasibility': typeof AdminEconomicFeasibilityRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/live-visitors': typeof AdminLiveVisitorsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/media/drive-upload': typeof ApiMediaDriveUploadRoute
  '/api/public/contact-notify': typeof ApiPublicContactNotifyRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/api/public/visitor-context': typeof ApiPublicVisitorContextRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/problem': typeof ProblemRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/solution': typeof SolutionRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/contact-info': typeof AdminContactInfoRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/design': typeof AdminDesignRoute
  '/admin/economic-feasibility': typeof AdminEconomicFeasibilityRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/live-visitors': typeof AdminLiveVisitorsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/api/media/drive-upload': typeof ApiMediaDriveUploadRoute
  '/api/public/contact-notify': typeof ApiPublicContactNotifyRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/api/public/visitor-context': typeof ApiPublicVisitorContextRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/features': typeof FeaturesRoute
  '/problem': typeof ProblemRoute
  '/roi-calculator': typeof RoiCalculatorRoute
  '/solution': typeof SolutionRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/contact-info': typeof AdminContactInfoRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/design': typeof AdminDesignRoute
  '/admin/economic-feasibility': typeof AdminEconomicFeasibilityRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/languages': typeof AdminLanguagesRoute
  '/admin/live-visitors': typeof AdminLiveVisitorsRoute
  '/admin/locations': typeof AdminLocationsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/navigation': typeof AdminNavigationRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin_/forgot-password': typeof AdminForgotPasswordRoute
  '/admin_/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/api/media/drive-upload': typeof ApiMediaDriveUploadRoute
  '/api/public/contact-notify': typeof ApiPublicContactNotifyRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/api/public/visitor-context': typeof ApiPublicVisitorContextRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/problem'
    | '/roi-calculator'
    | '/solution'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/backup'
    | '/admin/contact-info'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/design'
    | '/admin/economic-feasibility'
    | '/admin/faq'
    | '/admin/hero'
    | '/admin/inquiries'
    | '/admin/integrations'
    | '/admin/languages'
    | '/admin/live-visitors'
    | '/admin/locations'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/pages'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/users'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin/'
    | '/api/media/drive-upload'
    | '/api/public/contact-notify'
    | '/api/public/track'
    | '/api/public/visitor-context'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/problem'
    | '/roi-calculator'
    | '/solution'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/backup'
    | '/admin/contact-info'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/design'
    | '/admin/economic-feasibility'
    | '/admin/faq'
    | '/admin/hero'
    | '/admin/inquiries'
    | '/admin/integrations'
    | '/admin/languages'
    | '/admin/live-visitors'
    | '/admin/locations'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/pages'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/users'
    | '/admin/forgot-password'
    | '/admin/login'
    | '/admin'
    | '/api/media/drive-upload'
    | '/api/public/contact-notify'
    | '/api/public/track'
    | '/api/public/visitor-context'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/features'
    | '/problem'
    | '/roi-calculator'
    | '/solution'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/backup'
    | '/admin/contact-info'
    | '/admin/content'
    | '/admin/dashboard'
    | '/admin/design'
    | '/admin/economic-feasibility'
    | '/admin/faq'
    | '/admin/hero'
    | '/admin/inquiries'
    | '/admin/integrations'
    | '/admin/languages'
    | '/admin/live-visitors'
    | '/admin/locations'
    | '/admin/media'
    | '/admin/navigation'
    | '/admin/pages'
    | '/admin/seo'
    | '/admin/settings'
    | '/admin/team'
    | '/admin/users'
    | '/admin_/forgot-password'
    | '/admin_/login'
    | '/admin/'
    | '/api/media/drive-upload'
    | '/api/public/contact-notify'
    | '/api/public/track'
    | '/api/public/visitor-context'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  FeaturesRoute: typeof FeaturesRoute
  ProblemRoute: typeof ProblemRoute
  RoiCalculatorRoute: typeof RoiCalculatorRoute
  SolutionRoute: typeof SolutionRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiMediaDriveUploadRoute: typeof ApiMediaDriveUploadRoute
  ApiPublicContactNotifyRoute: typeof ApiPublicContactNotifyRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
  ApiPublicVisitorContextRoute: typeof ApiPublicVisitorContextRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solution': {
      id: '/solution'
      path: '/solution'
      fullPath: '/solution'
      preLoaderRoute: typeof SolutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roi-calculator': {
      id: '/roi-calculator'
      path: '/roi-calculator'
      fullPath: '/roi-calculator'
      preLoaderRoute: typeof RoiCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problem': {
      id: '/problem'
      path: '/problem'
      fullPath: '/problem'
      preLoaderRoute: typeof ProblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/forgot-password': {
      id: '/admin_/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/navigation': {
      id: '/admin/navigation'
      path: '/navigation'
      fullPath: '/admin/navigation'
      preLoaderRoute: typeof AdminNavigationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/locations': {
      id: '/admin/locations'
      path: '/locations'
      fullPath: '/admin/locations'
      preLoaderRoute: typeof AdminLocationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live-visitors': {
      id: '/admin/live-visitors'
      path: '/live-visitors'
      fullPath: '/admin/live-visitors'
      preLoaderRoute: typeof AdminLiveVisitorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/languages': {
      id: '/admin/languages'
      path: '/languages'
      fullPath: '/admin/languages'
      preLoaderRoute: typeof AdminLanguagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faq': {
      id: '/admin/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminFaqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/economic-feasibility': {
      id: '/admin/economic-feasibility'
      path: '/economic-feasibility'
      fullPath: '/admin/economic-feasibility'
      preLoaderRoute: typeof AdminEconomicFeasibilityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/design': {
      id: '/admin/design'
      path: '/design'
      fullPath: '/admin/design'
      preLoaderRoute: typeof AdminDesignRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contact-info': {
      id: '/admin/contact-info'
      path: '/contact-info'
      fullPath: '/admin/contact-info'
      preLoaderRoute: typeof AdminContactInfoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backup': {
      id: '/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AdminBackupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/visitor-context': {
      id: '/api/public/visitor-context'
      path: '/api/public/visitor-context'
      fullPath: '/api/public/visitor-context'
      preLoaderRoute: typeof ApiPublicVisitorContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact-notify': {
      id: '/api/public/contact-notify'
      path: '/api/public/contact-notify'
      fullPath: '/api/public/contact-notify'
      preLoaderRoute: typeof ApiPublicContactNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/drive-upload': {
      id: '/api/media/drive-upload'
      path: '/api/media/drive-upload'
      fullPath: '/api/media/drive-upload'
      preLoaderRoute: typeof ApiMediaDriveUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBackupRoute: typeof AdminBackupRoute
  AdminContactInfoRoute: typeof AdminContactInfoRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDesignRoute: typeof AdminDesignRoute
  AdminEconomicFeasibilityRoute: typeof AdminEconomicFeasibilityRoute
  AdminFaqRoute: typeof AdminFaqRoute
  AdminHeroRoute: typeof AdminHeroRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminLanguagesRoute: typeof AdminLanguagesRoute
  AdminLiveVisitorsRoute: typeof AdminLiveVisitorsRoute
  AdminLocationsRoute: typeof AdminLocationsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminNavigationRoute: typeof AdminNavigationRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBackupRoute: AdminBackupRoute,
  AdminContactInfoRoute: AdminContactInfoRoute,
  AdminContentRoute: AdminContentRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDesignRoute: AdminDesignRoute,
  AdminEconomicFeasibilityRoute: AdminEconomicFeasibilityRoute,
  AdminFaqRoute: AdminFaqRoute,
  AdminHeroRoute: AdminHeroRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminLanguagesRoute: AdminLanguagesRoute,
  AdminLiveVisitorsRoute: AdminLiveVisitorsRoute,
  AdminLocationsRoute: AdminLocationsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminNavigationRoute: AdminNavigationRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  FeaturesRoute: FeaturesRoute,
  ProblemRoute: ProblemRoute,
  RoiCalculatorRoute: RoiCalculatorRoute,
  SolutionRoute: SolutionRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiMediaDriveUploadRoute: ApiMediaDriveUploadRoute,
  ApiPublicContactNotifyRoute: ApiPublicContactNotifyRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
  ApiPublicVisitorContextRoute: ApiPublicVisitorContextRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
